# Generated by Django 4.2.1 on 2023-07-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_healthdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdetails',
            old_name='blood_sugar',
            new_name='blood_pressure',
        ),
    ]
